apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80       # 클러스터 내에서 서비스가 사용할 포트
      targetPort: 8080  # 컨테이너의 포트
      nodePort: 30000   # 노드에서 사용할 포트
  type: NodePort
