#-------------------------------------
# type 1
#-------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: my-userservice
spec:
  selector:
    app: my-userservice
  ports:
    - protocol: TCP
      port: 80 # sevice 가 클러스터 내에서 서비스가 사용하는 포트
      targetPort: 8080  # 컨테이너에서 사용할 포트
  type: LoadBalancer

##-------------------------------------
## type 2 nodeport
##-------------------------------------
#apiVersion: v1
#kind: Service
#metadata:
#  name: tomcat-service
#spec:
#  selector:
#    app: tomcat
#  ports:
#    - protocol: TCP
#      port: 80       # 클러스터 내에서 서비스가 사용할 포트
#      targetPort: 8080  # 컨테이너의 포트
#      nodePort: 30000   # 노드에서 사용할 포트
#  type: NodePort
#
